/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import dao.ConnectionFactory;
import entity.CadastroComprador;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import jpa.CadastroCompradorDAO;

/**
 *
 * @author gusta
 */
public class InternalCadastro extends javax.swing.JInternalFrame {

    private Connection conn;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private static InternalCadastro instance;

    public static InternalCadastro getInstance() {
        if (instance == null) {
            instance = new InternalCadastro();
        }
        return instance;
    }
    private CadastroCompradorDAO cadastroCompradorDAO;
    private CadastroComprador comprador;

    /**
     * Creates new form InternalCadastro
     */
    public InternalCadastro() {
        initComponents();
        conn = ConnectionFactory.getConnection();

        //this.getContentPane().setBackground(Color.decode("#1d5e69"));
        // Codigo para definir a cor do jTabblaPane selecionado
        //this.txtNome.setBackground(Color.decode("#263238"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCadPessoa = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblDataNasc = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        lblProfissao = new javax.swing.JLabel();
        txtProfissao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRenda = new javax.swing.JTextField();
        lblTelefone1 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        txtTelefone2 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        BoxUF = new javax.swing.JComboBox<>();
        lblCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BoxEstadoCivil = new javax.swing.JComboBox<>();
        lblNomeConjuge = new javax.swing.JLabel();
        txtNomeConjuge = new javax.swing.JTextField();
        lblCPFConjuge = new javax.swing.JLabel();
        txtCPFConjuge = new javax.swing.JTextField();
        lblDataNascConjuge = new javax.swing.JLabel();
        txtDataNascConjuge = new javax.swing.JTextField();
        txtProfissaoConjuge = new javax.swing.JTextField();
        txtRendaConjuge = new javax.swing.JTextField();
        lblProfissaoConjuge = new javax.swing.JLabel();
        lblRendaConjuge = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        boxLogradouro = new javax.swing.JComboBox<>();
        btnPesquisar1 = new javax.swing.JButton();
        btnNovo1 = new javax.swing.JButton();
        brnEditar1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        panelCadImovel = new javax.swing.JPanel();
        panelVendedor = new javax.swing.JPanel();
        lblCPF_Vend1 = new javax.swing.JLabel();
        txtCPFVendConj = new javax.swing.JTextField();
        lblNomeVend1 = new javax.swing.JLabel();
        txtNomeVend1 = new javax.swing.JTextField();
        lblCidadeVend = new javax.swing.JLabel();
        txtCidadeVend = new javax.swing.JTextField();
        lblBairroVend = new javax.swing.JLabel();
        txtBairroVend = new javax.swing.JTextField();
        boxImovel1 = new javax.swing.JComboBox<>();
        lblUFVend = new javax.swing.JLabel();
        lblCEPVend = new javax.swing.JLabel();
        txtCEP_Vend = new javax.swing.JTextField();
        lblNumeroVend = new javax.swing.JLabel();
        txtNumeroVend = new javax.swing.JTextField();
        lblComplVend = new javax.swing.JLabel();
        txtCompIVend = new javax.swing.JTextField();
        lblEndVend = new javax.swing.JLabel();
        txtEndVend = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boxVend = new javax.swing.JComboBox<>();
        lblEmailVend = new javax.swing.JLabel();
        txtEmailVend = new javax.swing.JTextField();
        lblCPF_Vend = new javax.swing.JLabel();
        txtCPFVend = new javax.swing.JTextField();
        lblNomeVend = new javax.swing.JLabel();
        txtNomeVend = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        boxLogradouroImovel1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtTelVend = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCelVend = new javax.swing.JTextField();
        panelImovel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        boxLogradouroImovel = new javax.swing.JComboBox<>();
        txtCompImovel = new javax.swing.JTextField();
        txtCEP_Imovel = new javax.swing.JTextField();
        boxImovel = new javax.swing.JComboBox<>();
        txtNumeroImovel = new javax.swing.JTextField();
        lblUFImovel = new javax.swing.JLabel();
        lblNumeroImovel = new javax.swing.JLabel();
        lblCEPImovel = new javax.swing.JLabel();
        lblComplImovel = new javax.swing.JLabel();
        txtBairroImovel = new javax.swing.JTextField();
        lblBairroImovel = new javax.swing.JLabel();
        lblCidadeImovel = new javax.swing.JLabel();
        txtCidadeImovel = new javax.swing.JTextField();
        lblEnderecoImovel = new javax.swing.JLabel();
        txtEnderecoImovel = new javax.swing.JTextField();
        txtIdImovel = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        brnEditar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setTitle("..:Cadastro:..");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/local-na-rede-internet (2).png"))); // NOI18N
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(1500, 900));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N

        panelCadPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 94, 105)), "Cadastro de Pessoa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 30), new java.awt.Color(124, 188, 154))); // NOI18N
        panelCadPessoa.setLayout(null);

        lblNome.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNome.setText("Nome:");
        panelCadPessoa.add(lblNome);
        lblNome.setBounds(190, 130, 53, 25);

        txtNome.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        panelCadPessoa.add(txtNome);
        txtNome.setBounds(260, 120, 720, 30);

        lblCPF.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCPF.setText("CPF:");
        panelCadPessoa.add(lblCPF);
        lblCPF.setBounds(990, 130, 34, 25);

        txtCPF.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtCPF);
        txtCPF.setBounds(1040, 120, 230, 30);

        lblDataNasc.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblDataNasc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataNasc.setText("Data de Nascimento:");
        panelCadPessoa.add(lblDataNasc);
        lblDataNasc.setBounds(80, 190, 165, 25);

        txtDataNasc.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtDataNasc);
        txtDataNasc.setBounds(260, 180, 180, 30);

        lblProfissao.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblProfissao.setText("Profissão:");
        panelCadPessoa.add(lblProfissao);
        lblProfissao.setBounds(460, 190, 77, 25);

        txtProfissao.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtProfissao);
        txtProfissao.setBounds(550, 180, 430, 30);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel2.setText("Renda Líquida:");
        panelCadPessoa.add(jLabel2);
        jLabel2.setBounds(990, 190, 116, 25);

        txtRenda.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtRenda);
        txtRenda.setBounds(1120, 180, 150, 30);

        lblTelefone1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblTelefone1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelefone1.setText("Telefone:");
        panelCadPessoa.add(lblTelefone1);
        lblTelefone1.setBounds(180, 250, 71, 25);

        txtTelefone.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtTelefone);
        txtTelefone.setBounds(260, 240, 165, 30);

        txtTelefone2.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        txtTelefone2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTelefone2.setText("Celular:");
        panelCadPessoa.add(txtTelefone2);
        txtTelefone2.setBounds(440, 250, 60, 25);

        txtCelular.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtCelular);
        txtCelular.setBounds(510, 240, 165, 30);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel3.setText("E-mail:");
        panelCadPessoa.add(jLabel3);
        jLabel3.setBounds(690, 250, 53, 25);

        txtEmail.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtEmail);
        txtEmail.setBounds(750, 240, 520, 30);

        lblEndereco.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblEndereco.setText("Endereço:");
        panelCadPessoa.add(lblEndereco);
        lblEndereco.setBounds(420, 310, 80, 25);

        txtEndereco.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtEndereco);
        txtEndereco.setBounds(500, 300, 310, 30);

        lblNumero.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblNumero.setText("Nº");
        panelCadPessoa.add(lblNumero);
        lblNumero.setBounds(820, 310, 21, 25);

        txtNumero.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtNumero);
        txtNumero.setBounds(850, 300, 60, 30);

        lblComplemento.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblComplemento.setText("Complemento:");
        panelCadPessoa.add(lblComplemento);
        lblComplemento.setBounds(920, 310, 118, 25);

        txtComplemento.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtComplemento);
        txtComplemento.setBounds(1050, 300, 220, 30);

        lblBairro.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblBairro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBairro.setText("Bairro:");
        panelCadPessoa.add(lblBairro);
        lblBairro.setBounds(200, 370, 50, 25);

        txtBairro.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtBairro);
        txtBairro.setBounds(260, 360, 310, 30);

        lblCidade.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCidade.setText("Cidade:");
        panelCadPessoa.add(lblCidade);
        lblCidade.setBounds(580, 370, 59, 25);

        txtCidade.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtCidade);
        txtCidade.setBounds(650, 360, 290, 30);

        lblUF.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblUF.setText("UF:");
        panelCadPessoa.add(lblUF);
        lblUF.setBounds(950, 370, 25, 25);

        BoxUF.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        BoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        panelCadPessoa.add(BoxUF);
        BoxUF.setBounds(980, 360, 100, 30);

        lblCEP.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCEP.setText("CEP:");
        panelCadPessoa.add(lblCEP);
        lblCEP.setBounds(1090, 370, 34, 25);

        txtCEP.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtCEP);
        txtCEP.setBounds(1130, 360, 140, 30);

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Estado Civil:");
        panelCadPessoa.add(jLabel4);
        jLabel4.setBounds(150, 480, 95, 20);

        BoxEstadoCivil.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        BoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Casado(a)", "Divorciado(a)", "Separado(a)", "Solteiro(a)", "Viuvo(a)" }));
        BoxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxEstadoCivilActionPerformed(evt);
            }
        });
        panelCadPessoa.add(BoxEstadoCivil);
        BoxEstadoCivil.setBounds(260, 470, 170, 30);

        lblNomeConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblNomeConjuge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeConjuge.setText("Nome Cônjuge:");
        panelCadPessoa.add(lblNomeConjuge);
        lblNomeConjuge.setBounds(120, 540, 124, 25);

        txtNomeConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        txtNomeConjuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeConjugeActionPerformed(evt);
            }
        });
        panelCadPessoa.add(txtNomeConjuge);
        txtNomeConjuge.setBounds(260, 530, 720, 30);

        lblCPFConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCPFConjuge.setText("CPF:");
        panelCadPessoa.add(lblCPFConjuge);
        lblCPFConjuge.setBounds(990, 540, 34, 25);

        txtCPFConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtCPFConjuge);
        txtCPFConjuge.setBounds(1040, 530, 230, 30);

        lblDataNascConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblDataNascConjuge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataNascConjuge.setText("Data de Nascimento:");
        panelCadPessoa.add(lblDataNascConjuge);
        lblDataNascConjuge.setBounds(80, 600, 165, 25);

        txtDataNascConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtDataNascConjuge);
        txtDataNascConjuge.setBounds(270, 590, 180, 30);

        txtProfissaoConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtProfissaoConjuge);
        txtProfissaoConjuge.setBounds(550, 590, 430, 30);

        txtRendaConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelCadPessoa.add(txtRendaConjuge);
        txtRendaConjuge.setBounds(1120, 590, 150, 30);

        lblProfissaoConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblProfissaoConjuge.setText("Profissão:");
        panelCadPessoa.add(lblProfissaoConjuge);
        lblProfissaoConjuge.setBounds(460, 600, 77, 25);

        lblRendaConjuge.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblRendaConjuge.setText("Renda Líquida:");
        panelCadPessoa.add(lblRendaConjuge);
        lblRendaConjuge.setBounds(990, 600, 116, 25);
        panelCadPessoa.add(jSeparator1);
        jSeparator1.setBounds(90, 430, 1180, 20);

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Logradouro:");
        panelCadPessoa.add(jLabel7);
        jLabel7.setBounds(150, 310, 100, 25);

        boxLogradouro.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        boxLogradouro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUA", "AVENIDA", "ESTRADA", "RODOVIA" }));
        panelCadPessoa.add(boxLogradouro);
        boxLogradouro.setBounds(260, 300, 150, 40);

        btnPesquisar1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnPesquisar1.setForeground(new java.awt.Color(51, 51, 51));
        btnPesquisar1.setText("Pesquisar");
        btnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar1ActionPerformed(evt);
            }
        });
        panelCadPessoa.add(btnPesquisar1);
        btnPesquisar1.setBounds(110, 680, 175, 70);

        btnNovo1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnNovo1.setForeground(new java.awt.Color(51, 51, 51));
        btnNovo1.setText("Novo");
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });
        panelCadPessoa.add(btnNovo1);
        btnNovo1.setBounds(340, 680, 175, 70);

        brnEditar1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        brnEditar1.setForeground(new java.awt.Color(51, 51, 51));
        brnEditar1.setText("Editar");
        brnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnEditar1ActionPerformed(evt);
            }
        });
        panelCadPessoa.add(brnEditar1);
        brnEditar1.setBounds(580, 680, 175, 70);

        btnExcluir.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(51, 51, 51));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        panelCadPessoa.add(btnExcluir);
        btnExcluir.setBounds(840, 680, 175, 70);

        btnCancelar1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelar1.setText("Cancelar");
        panelCadPessoa.add(btnCancelar1);
        btnCancelar1.setBounds(1090, 680, 175, 70);

        jTabbedPane1.addTab("Cliente", panelCadPessoa);

        panelCadImovel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 94, 105)), "Cadastro de Imóvel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 30), new java.awt.Color(124, 188, 154))); // NOI18N
        panelCadImovel.setLayout(null);

        panelVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 153, 142)), "Dados dos Vendedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 24), new java.awt.Color(243, 225, 182))); // NOI18N
        panelVendedor.setLayout(null);

        lblCPF_Vend1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCPF_Vend1.setText("CPF:");
        panelVendedor.add(lblCPF_Vend1);
        lblCPF_Vend1.setBounds(930, 320, 34, 25);

        txtCPFVendConj.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtCPFVendConj);
        txtCPFVendConj.setBounds(980, 310, 260, 40);

        lblNomeVend1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblNomeVend1.setText("Nome Cônjuge:");
        panelVendedor.add(lblNomeVend1);
        lblNomeVend1.setBounds(20, 320, 124, 25);

        txtNomeVend1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtNomeVend1);
        txtNomeVend1.setBounds(150, 310, 750, 40);

        lblCidadeVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCidadeVend.setText("Cidade:");
        panelVendedor.add(lblCidadeVend);
        lblCidadeVend.setBounds(470, 220, 59, 25);

        txtCidadeVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtCidadeVend);
        txtCidadeVend.setBounds(540, 210, 290, 40);

        lblBairroVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblBairroVend.setText("Bairro:");
        panelVendedor.add(lblBairroVend);
        lblBairroVend.setBounds(90, 220, 50, 25);

        txtBairroVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtBairroVend);
        txtBairroVend.setBounds(150, 210, 310, 40);

        boxImovel1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        boxImovel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        panelVendedor.add(boxImovel1);
        boxImovel1.setBounds(870, 210, 100, 40);

        lblUFVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblUFVend.setText("UF:");
        panelVendedor.add(lblUFVend);
        lblUFVend.setBounds(840, 220, 25, 25);

        lblCEPVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCEPVend.setText("CEP:");
        panelVendedor.add(lblCEPVend);
        lblCEPVend.setBounds(990, 220, 34, 25);

        txtCEP_Vend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtCEP_Vend);
        txtCEP_Vend.setBounds(1040, 210, 200, 40);

        lblNumeroVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblNumeroVend.setText("Nº:");
        panelVendedor.add(lblNumeroVend);
        lblNumeroVend.setBounds(740, 170, 25, 25);

        txtNumeroVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtNumeroVend);
        txtNumeroVend.setBounds(770, 160, 60, 40);

        lblComplVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblComplVend.setText("Complemento:");
        panelVendedor.add(lblComplVend);
        lblComplVend.setBounds(840, 170, 118, 25);

        txtCompIVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtCompIVend);
        txtCompIVend.setBounds(970, 160, 270, 40);

        lblEndVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblEndVend.setText("Endereço:");
        panelVendedor.add(lblEndVend);
        lblEndVend.setBounds(320, 170, 80, 25);

        txtEndVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtEndVend);
        txtEndVend.setBounds(410, 160, 310, 40);

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel6.setText("Estado Civil:");
        panelVendedor.add(jLabel6);
        jLabel6.setBounds(50, 270, 95, 25);

        boxVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        boxVend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Casado(a)", "Divorciado(a)", "Separado(a)", "Solteiro(a)", "Viuvo(a)" }));
        panelVendedor.add(boxVend);
        boxVend.setBounds(150, 260, 170, 40);

        lblEmailVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblEmailVend.setText("E-mail:");
        panelVendedor.add(lblEmailVend);
        lblEmailVend.setBounds(90, 120, 53, 25);

        txtEmailVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtEmailVend);
        txtEmailVend.setBounds(150, 110, 470, 40);

        lblCPF_Vend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCPF_Vend.setText("CPF:");
        panelVendedor.add(lblCPF_Vend);
        lblCPF_Vend.setBounds(930, 70, 34, 25);

        txtCPFVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtCPFVend);
        txtCPFVend.setBounds(980, 60, 260, 40);

        lblNomeVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblNomeVend.setText("Nome:");
        panelVendedor.add(lblNomeVend);
        lblNomeVend.setBounds(90, 70, 53, 25);

        txtNomeVend.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelVendedor.add(txtNomeVend);
        txtNomeVend.setBounds(150, 60, 750, 40);

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Logradouro:");
        panelVendedor.add(jLabel9);
        jLabel9.setBounds(40, 170, 100, 25);

        boxLogradouroImovel1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        boxLogradouroImovel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUA", "AVENIDA", "ESTRADA", "RODOVIA" }));
        panelVendedor.add(boxLogradouroImovel1);
        boxLogradouroImovel1.setBounds(150, 160, 150, 40);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel1.setText("Telefone:");
        panelVendedor.add(jLabel1);
        jLabel1.setBounds(640, 120, 80, 25);
        panelVendedor.add(txtTelVend);
        txtTelVend.setBounds(720, 110, 210, 40);

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Celular:");
        panelVendedor.add(jLabel5);
        jLabel5.setBounds(950, 120, 60, 25);
        panelVendedor.add(txtCelVend);
        txtCelVend.setBounds(1020, 110, 220, 40);

        panelCadImovel.add(panelVendedor);
        panelVendedor.setBounds(20, 290, 1340, 440);

        panelImovel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 153, 142)), "Dados do Imóvel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 24), new java.awt.Color(243, 225, 182))); // NOI18N
        panelImovel.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Logradouro:");
        panelImovel.add(jLabel8);
        jLabel8.setBounds(50, 70, 100, 25);

        boxLogradouroImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        boxLogradouroImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUA", "AVENIDA", "ESTRADA", "RODOVIA" }));
        panelImovel.add(boxLogradouroImovel);
        boxLogradouroImovel.setBounds(160, 60, 150, 40);

        txtCompImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelImovel.add(txtCompImovel);
        txtCompImovel.setBounds(1030, 60, 260, 40);

        txtCEP_Imovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelImovel.add(txtCEP_Imovel);
        txtCEP_Imovel.setBounds(1100, 140, 190, 40);

        boxImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        boxImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        panelImovel.add(boxImovel);
        boxImovel.setBounds(920, 140, 100, 40);

        txtNumeroImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        txtNumeroImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroImovelActionPerformed(evt);
            }
        });
        panelImovel.add(txtNumeroImovel);
        txtNumeroImovel.setBounds(810, 60, 60, 40);

        lblUFImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblUFImovel.setText("UF:");
        panelImovel.add(lblUFImovel);
        lblUFImovel.setBounds(880, 150, 25, 25);

        lblNumeroImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblNumeroImovel.setText("Nº:");
        panelImovel.add(lblNumeroImovel);
        lblNumeroImovel.setBounds(770, 70, 25, 25);

        lblCEPImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCEPImovel.setText("CEP:");
        panelImovel.add(lblCEPImovel);
        lblCEPImovel.setBounds(1050, 150, 34, 25);

        lblComplImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblComplImovel.setText("Complemento:");
        panelImovel.add(lblComplImovel);
        lblComplImovel.setBounds(900, 70, 118, 25);

        txtBairroImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelImovel.add(txtBairroImovel);
        txtBairroImovel.setBounds(150, 140, 310, 40);

        lblBairroImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblBairroImovel.setText("Bairro:");
        panelImovel.add(lblBairroImovel);
        lblBairroImovel.setBounds(80, 150, 50, 25);

        lblCidadeImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblCidadeImovel.setText("Cidade:");
        panelImovel.add(lblCidadeImovel);
        lblCidadeImovel.setBounds(490, 150, 59, 25);

        txtCidadeImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelImovel.add(txtCidadeImovel);
        txtCidadeImovel.setBounds(560, 140, 290, 40);

        lblEnderecoImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblEnderecoImovel.setText("Endereço:");
        panelImovel.add(lblEnderecoImovel);
        lblEnderecoImovel.setBounds(340, 70, 77, 25);

        txtEnderecoImovel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        panelImovel.add(txtEnderecoImovel);
        txtEnderecoImovel.setBounds(430, 60, 310, 40);
        panelImovel.add(txtIdImovel);
        txtIdImovel.setBounds(330, 30, 6, 22);

        panelCadImovel.add(panelImovel);
        panelImovel.setBounds(20, 50, 1340, 220);

        btnPesquisar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(51, 51, 51));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        panelCadImovel.add(btnPesquisar);
        btnPesquisar.setBounds(120, 760, 175, 70);

        btnNovo.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(51, 51, 51));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panelCadImovel.add(btnNovo);
        btnNovo.setBounds(360, 760, 175, 70);

        brnEditar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        brnEditar.setForeground(new java.awt.Color(51, 51, 51));
        brnEditar.setText("Editar");
        panelCadImovel.add(brnEditar);
        brnEditar.setBounds(610, 760, 175, 70);

        btnImprimir.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(51, 51, 51));
        btnImprimir.setText("Imprimir");
        panelCadImovel.add(btnImprimir);
        btnImprimir.setBounds(850, 760, 175, 70);

        btnCancelar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelar.setText("Cancelar");
        panelCadImovel.add(btnCancelar);
        btnCancelar.setBounds(1090, 760, 175, 70);

        jTabbedPane1.addTab("Imóvel", panelCadImovel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 1491, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroImovelActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        adicionarImovel();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        adicionarComprador();
//        pesquisar_cliente();

    }//GEN-LAST:event_btnNovo1ActionPerformed

    private void btnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar1ActionPerformed
        pesquisar_comprador();

    }//GEN-LAST:event_btnPesquisar1ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisar_comprador();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtNomeConjugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeConjugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeConjugeActionPerformed

    private void BoxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxEstadoCivilActionPerformed
        if (BoxEstadoCivil.getSelectedItem().toString().equals("Casado(a)")) {
            txtNomeConjuge.setEnabled(true);
            txtCPFConjuge.setEnabled(true);
            txtDataNascConjuge.setEditable(true);
            txtProfissaoConjuge.setEnabled(true);
            txtRendaConjuge.setEnabled(true);
        } else {
            txtNomeConjuge.setEnabled(false);
            txtCPFConjuge.setEnabled(false);
            txtDataNascConjuge.setEditable(false);
            txtProfissaoConjuge.setEnabled(false);
            txtRendaConjuge.setEnabled(false);

        }
    }//GEN-LAST:event_BoxEstadoCivilActionPerformed

    private void brnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnEditar1ActionPerformed
        alterarComprador();
    }//GEN-LAST:event_brnEditar1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        removerComprado();
    }//GEN-LAST:event_btnExcluirActionPerformed
    // feito
    private void adicionarComprador() {
        String sql = "insert into tb_cadastropessoa(nome, cpf, dtNascimento, profissao, renda, telefone, celular, email, logradouro,endereco, numeroEnde, "
                + "complemento, bairro, cidade, uf, cep, estadoCivil, nomeConj, cpfConj, dtNascConj, profissaoConj, rendaConj) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?, ?, ?, ?)";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtCPF.getText());
            pst.setString(3, txtDataNasc.getText());
            pst.setString(4, txtProfissao.getText());
            pst.setString(5, txtRenda.getText());
            pst.setString(6, txtTelefone.getText());
            pst.setString(7, txtCelular.getText());
            pst.setString(8, txtEmail.getText());
            pst.setString(9, boxLogradouro.getSelectedItem().toString());
            pst.setString(10, txtEndereco.getText());
            pst.setString(11, txtNumero.getText());
            pst.setString(12, txtComplemento.getText());
            pst.setString(13, txtBairro.getText());
            pst.setString(14, txtCidade.getText());
            pst.setString(15, BoxUF.getSelectedItem().toString());
            pst.setString(16, txtCEP.getText());
            pst.setString(17, BoxEstadoCivil.getSelectedItem().toString());
            pst.setString(18, txtNomeConjuge.getText());
            pst.setString(19, txtCPFConjuge.getText());
            pst.setString(20, txtDataNascConjuge.getText());
            pst.setString(21, txtProfissaoConjuge.getText());
            pst.setString(22, txtRendaConjuge.getText());

            //campos obrigatórios
            if ((txtNome.getText().isEmpty()) || (txtCPF.getText().isEmpty()) || (txtDataNasc.getText().isEmpty()) || (txtProfissao.getText().isEmpty()) || (txtRenda.getText().isEmpty())
                    || (txtCelular.getText().isEmpty()) || (txtEmail.getText().isEmpty()) || (txtEndereco.getText().isEmpty()) || (txtBairro.getText().isEmpty())
                    || (txtCidade.getText().isEmpty()) || (txtCEP.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(this, "Dados adicionado com sucesso!");
                    limpar();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void alterarComprador() {
        String sql = "update tb_cadastropessoa set nome=?, cpf=?, dtNascimento=?, profissao=?, renda=?, telefone=?, celular=?, email=?, logradouro=?, endereco=? , numeroEnde=?, complemento=?, bairro=?, cidade=?, uf=?, cep=?, "
                + "estadoCivil=?, nomeConj=?, cpfConj=?, dtNascConj=?, profissaoConj=?, rendaConj=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtCPF.getText());
            pst.setString(3, txtDataNasc.getText());
            pst.setString(4, txtProfissao.getText());
            pst.setString(5, txtRenda.getText());
            pst.setString(6, txtTelefone.getText());
            pst.setString(7, txtCelular.getText());
            pst.setString(8, txtEmail.getText());
            pst.setString(9, boxLogradouro.getSelectedItem().toString());
            pst.setString(10, txtEndereco.getText());
            pst.setString(11, txtNumero.getText());
            pst.setString(12, txtComplemento.getText());
            pst.setString(13, txtBairro.getText());
            pst.setString(14, txtCidade.getText());
            pst.setString(15, BoxUF.getSelectedItem().toString());
            pst.setString(16, txtCEP.getText());
            pst.setString(17, BoxEstadoCivil.getSelectedItem().toString());
            pst.setString(18, txtNomeConjuge.getText());
            pst.setString(19, txtCPFConjuge.getText());
            pst.setString(20, txtDataNascConjuge.getText());
            pst.setString(21, txtProfissaoConjuge.getText());
            pst.setString(22, txtRendaConjuge.getText());

            if ((txtNome.getText().isEmpty()) || (txtCPF.getText().isEmpty()) || (txtDataNasc.getText().isEmpty()) || (txtProfissao.getText().isEmpty()) || (txtRenda.getText().isEmpty())
                    || (txtCelular.getText().isEmpty()) || (txtEmail.getText().isEmpty()) || (txtEndereco.getText().isEmpty()) || (txtBairro.getText().isEmpty())
                    || (txtCidade.getText().isEmpty()) || (txtCEP.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(this, "Dados alterado com sucesso!");
                    limpar();
                    txtNome.setText(null);
                    txtCPF.setText(null);
                    txtDataNasc.setText(null);
                    txtProfissao.setText(null);
                    txtRenda.setText(null);
                    txtTelefone.setText(null);
                    txtCelular.setText(null);
                    txtEmail.setText(null);
                    boxLogradouro.setSelectedItem(null);
                    txtEndereco.setText(null);
                    txtNumero.setText(null);
                    txtComplemento.setText(null);
                    txtBairro.setText(null);
                    txtCidade.setText(null);
                    txtCEP.setText(null);
                    BoxEstadoCivil.setSelectedItem(null);
                    txtNomeConjuge.setText(null);
                    txtCPFConjuge.setText(null);
                    txtDataNascConjuge.setText(null);
                    txtProfissaoConjuge.setText(null);
                    txtRendaConjuge.setText(null);
                    btnNovo1.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }
    }

    // feito
    private void removerComprado() {
        //a estrutura abaixo confirma a remoção do cliente
        int confirma = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja remover este cliente ?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from tb_cadastropessoa where cpf = ?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtCPF.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(this, "Cliente Removido com sucesso");
                    txtNome.setText(null);
                    txtCPF.setText(null);
                    txtDataNasc.setText(null);
                    txtProfissao.setText(null);
                    txtRenda.setText(null);
                    txtTelefone.setText(null);
                    txtCelular.setText(null);
                    txtEmail.setText(null);
                    boxLogradouro.setSelectedItem(null);
                    txtEndereco.setText(null);
                    txtNumero.setText(null);
                    txtComplemento.setText(null);
                    txtBairro.setText(null);
                    txtCidade.setText(null);
                    txtCEP.setText(null);
                    BoxEstadoCivil.setSelectedItem(null);
                    txtNomeConjuge.setText(null);
                    txtCPFConjuge.setText(null);
                    txtDataNascConjuge.setText(null);
                    txtProfissaoConjuge.setText(null);
                    txtRendaConjuge.setText(null);
                    boxLogradouroImovel.setSelectedItem(null);
                    txtEnderecoImovel.setText(null);
                    txtNumeroImovel.setText(null);
                    txtCompImovel.setText(null);
                    txtBairroImovel.setText(null);
                    txtCidadeImovel.setText(null);
                    boxImovel.setSelectedItem(null);
                    txtCEP_Imovel.setText(null);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);

            }
        }
    }

    private void pesquisar_comprador() {
        String sql = "select * from tb_cadastropessoa where cpf = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtCPF.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtNome.setText(rs.getString(1));
                txtCPF.setText(rs.getString(2));
                txtDataNasc.setText(rs.getString(3));
                txtProfissao.setText(rs.getString(4));
                txtRenda.setText(rs.getString(5));
                txtTelefone.setText(rs.getString(6));
                txtCelular.setText(rs.getString(7));
                txtEmail.setText(rs.getString(8));
                boxLogradouro.setSelectedItem(rs.getString(9));
                txtEndereco.setText(rs.getString(10));
                txtNumero.setText(rs.getString(11));
                txtComplemento.setText(rs.getString(12));
                txtBairro.setText(rs.getString(13));
                txtCidade.setText(rs.getString(14));
                BoxUF.setSelectedItem(rs.getString(15));
                txtCEP.setText(rs.getString(16));
                BoxEstadoCivil.setSelectedItem(rs.getString(17));
                txtNomeConjuge.setText(rs.getString(18));
                txtCPFConjuge.setText(rs.getString(19));
                txtDataNascConjuge.setText(rs.getString(20));
                txtProfissaoConjuge.setText(rs.getString(21));
                txtRendaConjuge.setText(rs.getString(22));
            } else {
                JOptionPane.showMessageDialog(this, "Dados não localizados, informe o CPF correto");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void adicionarImovel() {
        String sql = "insert into tb_cadastroimovel(logradouroImovel, enderecoImovel, numeroEndeImovel, complementoImovel, bairroImovel, cidadeImovel, "
                + "ufImovel, cepImovel, vendedor) values (?,?,?,?,?,?,?,?,?)";

        try {
            //imovel
            pst = conn.prepareStatement(sql);
            pst.setString(1, boxLogradouroImovel.getSelectedItem().toString());
            pst.setString(2, txtEnderecoImovel.getText());
            pst.setString(3, txtNumeroImovel.getText());
            pst.setString(4, txtCompImovel.getText());
            pst.setString(5, txtBairroImovel.getText());
            pst.setString(6, txtCidadeImovel.getText());
            pst.setString(7, boxImovel.getSelectedItem().toString());
            pst.setString(8, txtCEP_Imovel.getText());
            pst.setString(9, txtCPFVend.getText());

            if ((txtCPFVend.getText().toString().isEmpty()) || (boxLogradouroImovel.getSelectedItem().toString().isEmpty()) || (txtEnderecoImovel.getText().isEmpty()) || (txtNumeroImovel.getText().isEmpty())
                    || txtCompImovel.getText().isEmpty() || txtBairroImovel.getText().isEmpty() || txtCidadeImovel.getText().isEmpty() || boxImovel.getSelectedItem().toString().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            } else {
                int adicionado = pst.executeUpdate();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        try {
            String sql2 = "insert into tb_cadastrovendedor(nome, cpf, email, telefone, celular, logradouro, endereco, numeroEnde, "
                    + "complemento, bairro, cidade, uf, cep, estadoCivil, nomeConj, cpfConj) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(sql2);
            pst.setString(1, txtNomeVend.getText());
            pst.setString(2, txtCPFVend.getText());
            pst.setString(3, txtEmailVend.getText());
            pst.setString(4, txtTelVend.getText());
            pst.setString(5, txtCelVend.getText());
            pst.setString(6, boxLogradouroImovel1.getSelectedItem().toString());
            pst.setString(7, txtEndVend.getText());
            pst.setString(8, txtNumeroVend.getText());
            pst.setString(9, txtCompIVend.getText());
            pst.setString(10, txtBairroVend.getText());
            pst.setString(11, txtCidadeVend.getText());
            pst.setString(12, boxImovel1.getSelectedItem().toString());
            pst.setString(13, txtCEP_Vend.getText());
            pst.setString(14, boxVend.getSelectedItem().toString());
            pst.setString(15, txtNomeVend1.getText());
            pst.setString(16, txtCPFVendConj.getText());

            int adicionado = pst.executeUpdate();
            limpar();
            JOptionPane.showMessageDialog(this, "Dados inseridos com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void pesquisar_dadosImovel() {
        String sql = "select * from tb_cadastropessoa where cpf = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtCPF.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtNome.setText(rs.getString(1));
                txtCPF.setText(rs.getString(2));
                txtDataNasc.setText(rs.getString(3));
                txtProfissao.setText(rs.getString(4));
                txtRenda.setText(rs.getString(5));
                txtTelefone.setText(rs.getString(6));
                txtCelular.setText(rs.getString(7));
                txtEmail.setText(rs.getString(8));
                boxLogradouro.setSelectedItem(rs.getString(9));
                txtEndereco.setText(rs.getString(10));
                txtNumero.setText(rs.getString(11));
                txtComplemento.setText(rs.getString(12));
                txtBairro.setText(rs.getString(13));
                txtCidade.setText(rs.getString(14));
                BoxUF.setSelectedItem(rs.getString(15));
                txtCEP.setText(rs.getString(16));
                BoxEstadoCivil.setSelectedItem(rs.getString(17));
                txtNomeConjuge.setText(rs.getString(18));
                txtCPFConjuge.setText(rs.getString(19));
                txtDataNascConjuge.setText(rs.getString(20));
                txtProfissaoConjuge.setText(rs.getString(21));
                txtRendaConjuge.setText(rs.getString(22));
            } else {
                JOptionPane.showMessageDialog(this, "Dados não localizados, informe o CPF correto");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void limpar() {

        //comprador
        txtNome.setText(null);
        txtCPF.setText(null);
        txtDataNasc.setText(null);
        txtProfissao.setText(null);
        txtRenda.setText(null);
        txtTelefone.setText(null);
        txtCelular.setText(null);
        txtEmail.setText(null);
        boxLogradouro.setSelectedItem(null);
        txtEndereco.setText(null);
        txtNumero.setText(null);
        txtComplemento.setText(null);
        txtBairro.setText(null);
        txtCidade.setText(null);
        txtCEP.setText(null);
        BoxEstadoCivil.setSelectedItem(null);
        txtNomeConjuge.setText(null);
        txtCPFConjuge.setText(null);
        txtDataNascConjuge.setText(null);
        txtProfissaoConjuge.setText(null);
        txtRendaConjuge.setText(null);
        boxLogradouroImovel.setSelectedItem(null);
        txtEnderecoImovel.setText(null);
        txtNumeroImovel.setText(null);
        txtCompImovel.setText(null);
        txtBairroImovel.setText(null);
        txtCidadeImovel.setText(null);
        boxImovel.setSelectedItem(null);
        txtCEP_Imovel.setText(null);

        //vendedores
        txtNomeVend.setText(null);
        txtCPFVend.setText(null);
        txtTelVend.setText(null);
        txtCelVend.setText(null);
        txtEmailVend.setText(null);
        boxLogradouroImovel1.setSelectedItem(null);
        txtEndVend.setText(null);
        txtNumeroVend.setText(null);
        txtCompIVend.setText(null);
        txtBairroVend.setText(null);
        txtCidadeVend.setText(null);
        txtCEP_Vend.setText(null);
        boxVend.setSelectedItem(null);
        txtNomeVend1.setText(null);
        txtCPFVendConj.setText(null);
    }

    private void alterarImovel() {
        String sql = "update tb_cadastroimovel set logradouroImovel=?, enderecoImovel=?, numeroEndeImovel=?, complementoImovel=?, bairroImovel=?, cidadeImovel=?, "
                + "ufImovel=?, cepImovel=?";

        try {
            //vendedor
            pst = conn.prepareStatement(sql);
            pst.setString(1, boxLogradouroImovel.getSelectedItem().toString());
            pst.setString(2, txtEnderecoImovel.getText());
            pst.setString(3, txtNumeroImovel.getText());
            pst.setString(4, txtCompImovel.getText());
            pst.setString(5, txtBairroImovel.getText());
            pst.setString(6, txtCidadeImovel.getText());
            pst.setString(7, boxImovel.getSelectedItem().toString());
            pst.setString(8, txtCEP_Imovel.getText());

            if ((txtNome.getText().isEmpty()) || (txtCPF.getText().isEmpty()) || (txtDataNasc.getText().isEmpty()) || (txtProfissao.getText().isEmpty()) || (txtRenda.getText().isEmpty())
                    || (txtCelular.getText().isEmpty()) || (txtEmail.getText().isEmpty()) || (txtEndereco.getText().isEmpty()) || (txtBairro.getText().isEmpty())
                    || (txtCidade.getText().isEmpty()) || (txtCEP.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(this, "Dados alterado com sucesso!");
                    boxLogradouroImovel.setSelectedItem(null);
                    txtEnderecoImovel.setText(null);
                    txtNumeroImovel.setText(null);
                    txtCompImovel.setText(null);
                    txtBairroImovel.setText(null);
                    txtCidadeImovel.setText(null);
                    boxImovel.setSelectedItem(null);
                    txtCEP_Imovel.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxEstadoCivil;
    private javax.swing.JComboBox<String> BoxUF;
    private javax.swing.JComboBox<String> boxImovel;
    private javax.swing.JComboBox<String> boxImovel1;
    private javax.swing.JComboBox<String> boxLogradouro;
    private javax.swing.JComboBox<String> boxLogradouroImovel;
    private javax.swing.JComboBox<String> boxLogradouroImovel1;
    private javax.swing.JComboBox<String> boxVend;
    private javax.swing.JButton brnEditar;
    private javax.swing.JButton brnEditar1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBairroImovel;
    private javax.swing.JLabel lblBairroVend;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCEPImovel;
    private javax.swing.JLabel lblCEPVend;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPFConjuge;
    private javax.swing.JLabel lblCPF_Vend;
    private javax.swing.JLabel lblCPF_Vend1;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCidadeImovel;
    private javax.swing.JLabel lblCidadeVend;
    private javax.swing.JLabel lblComplImovel;
    private javax.swing.JLabel lblComplVend;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblDataNascConjuge;
    private javax.swing.JLabel lblEmailVend;
    private javax.swing.JLabel lblEndVend;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEnderecoImovel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeConjuge;
    private javax.swing.JLabel lblNomeVend;
    private javax.swing.JLabel lblNomeVend1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroImovel;
    private javax.swing.JLabel lblNumeroVend;
    private javax.swing.JLabel lblProfissao;
    private javax.swing.JLabel lblProfissaoConjuge;
    private javax.swing.JLabel lblRendaConjuge;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JLabel lblUF;
    private javax.swing.JLabel lblUFImovel;
    private javax.swing.JLabel lblUFVend;
    private javax.swing.JPanel panelCadImovel;
    private javax.swing.JPanel panelCadPessoa;
    private javax.swing.JPanel panelImovel;
    private javax.swing.JPanel panelVendedor;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBairroImovel;
    private javax.swing.JTextField txtBairroVend;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCEP_Imovel;
    private javax.swing.JTextField txtCEP_Vend;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPFConjuge;
    private javax.swing.JTextField txtCPFVend;
    private javax.swing.JTextField txtCPFVendConj;
    private javax.swing.JTextField txtCelVend;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCidadeImovel;
    private javax.swing.JTextField txtCidadeVend;
    private javax.swing.JTextField txtCompIVend;
    private javax.swing.JTextField txtCompImovel;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtDataNascConjuge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailVend;
    private javax.swing.JTextField txtEndVend;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEnderecoImovel;
    private javax.swing.JTextField txtIdImovel;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeConjuge;
    private javax.swing.JTextField txtNomeVend;
    private javax.swing.JTextField txtNomeVend1;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroImovel;
    private javax.swing.JTextField txtNumeroVend;
    private javax.swing.JTextField txtProfissao;
    private javax.swing.JTextField txtProfissaoConjuge;
    private javax.swing.JTextField txtRenda;
    private javax.swing.JTextField txtRendaConjuge;
    private javax.swing.JTextField txtTelVend;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JLabel txtTelefone2;
    // End of variables declaration//GEN-END:variables
}
