/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

/**
 *
 * @author gusta
 */
public class InternalRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalRelatorio
     */
    private static InternalRelatorio instance;

    public static InternalRelatorio getInstance() {
        if (instance == null) {
            instance = new InternalRelatorio();
        } 
        return instance;
    }

    public InternalRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setIconifiable(true);
        setTitle("..:Relatório:..");
        setMaximumSize(new java.awt.Dimension(1440, 884));
        setMinimumSize(new java.awt.Dimension(1440, 884));
        setPreferredSize(new java.awt.Dimension(1500, 1000));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 40, 580, 580);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(840, 50, 250, 250);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1090, 460, 150, 50);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(720, 350, 150, 50);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(900, 350, 150, 50);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(1090, 350, 150, 50);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(720, 460, 150, 50);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(900, 460, 150, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
