/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.ControleAcesso.DialogAcesso;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatGruvboxDarkMediumIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDarkerContrastIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanContrastIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialOceanicContrastIJTheme;
import dao.ConnectionFactory;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class ViewIniciar extends javax.swing.JFrame {

    private Connection conn;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form ViewIniciar
     */
    public ViewIniciar() {
        DialogLogin telaLogin = new DialogLogin(this, true);
        telaLogin.setVisible(true);
        if (telaLogin.getAutenticado()) {
            initComponents();
            conn = ConnectionFactory.getConnection();
        }
    }

    private void totalComissao() {
        String sql = "select ROUND(SUM(valor)*0.013,2) from tb_contrato";
        try {
            //as linhas abaixo preparam a consulta em função do que foi 
            //digitado nas caixas de texto. O ? é substituído pelo conteúdo
            //das variáveis que são armazenadas em pst.setString
            pst = conn.prepareStatement(sql);
            //a linha abaixo executa a query(consulta)
            rs = pst.executeQuery();
            //se existir um usuário e senha correspondente
            //a estrutura abaixo faz o tratamento do perfil do usuário
            rs.next();
            lblComissao.setText(rs.getString(1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void valorComissao() {
        String sql = "select ROUND(SUM(valor),2) from tb_contrato";
        try {
            //as linhas abaixo preparam a consulta em função do que foi 
            //digitado nas caixas de texto. O ? é substituído pelo conteúdo
            //das variáveis que são armazenadas em pst.setString
            pst = conn.prepareStatement(sql);
            //a linha abaixo executa a query(consulta)
            rs = pst.executeQuery();
            //se existir um usuário e senha correspondente
            //a estrutura abaixo faz o tratamento do perfil do usuário
            rs.next();
            lblTotal.setText(rs.getString(1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void medianaComissao() {
        String sql = "select ROUND(SUM(valor),2) from tb_contrato";
        try {
            //as linhas abaixo preparam a consulta em função do que foi 
            //digitado nas caixas de texto. O ? é substituído pelo conteúdo
            //das variáveis que são armazenadas em pst.setString
            pst = conn.prepareStatement(sql);
            //a linha abaixo executa a query(consulta)
            rs = pst.executeQuery();
            //se existir um usuário e senha correspondente
            //a estrutura abaixo faz o tratamento do perfil do usuário
            rs.next();
            lblTotal.setText(rs.getString(1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void totalContrato() {
        String sql = "select COUNT(id) from tb_contrato";
        try {
            //as linhas abaixo preparam a consulta em função do que foi 
            //digitado nas caixas de texto. O ? é substituído pelo conteúdo
            //das variáveis que são armazenadas em pst.setString
            pst = conn.prepareStatement(sql);
            //a linha abaixo executa a query(consulta)
            rs = pst.executeQuery();
            //se existir um usuário e senha correspondente
            //a estrutura abaixo faz o tratamento do perfil do usuário
            rs.next();
            lblContrato.setText(rs.getString(1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSimulacao = new javax.swing.JButton();
        btnContrato = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnInformacoes = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblComissao = new javax.swing.JLabel();
        lblContrato = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCedula1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCedula2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".::ImobSoftware::.");
        setBackground(new java.awt.Color(51, 51, 51));
        setExtendedState(6);
        setMaximumSize(new java.awt.Dimension(1440, 850));
        setMinimumSize(new java.awt.Dimension(1440, 850));
        setPreferredSize(new java.awt.Dimension(1440, 850));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(29, 94, 105));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        txtData.setFont(new java.awt.Font("MS UI Gothic", 0, 30)); // NOI18N
        txtData.setForeground(new java.awt.Color(243, 225, 182));
        txtData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtData.setText("Data");
        jPanel1.add(txtData);
        txtData.setBounds(20, 780, 321, 31);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/LogoSemFundo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 80, 187, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/LogoSDC.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 998, 80, 40);

        btnSimulacao.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        btnSimulacao.setForeground(new java.awt.Color(51, 51, 51));
        btnSimulacao.setText("Simulação");
        btnSimulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulacaoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimulacao);
        btnSimulacao.setBounds(50, 460, 285, 50);

        btnContrato.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        btnContrato.setForeground(new java.awt.Color(51, 51, 51));
        btnContrato.setText("Contrato");
        btnContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratoActionPerformed(evt);
            }
        });
        jPanel1.add(btnContrato);
        btnContrato.setBounds(50, 540, 285, 50);

        btnRelatorio.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(51, 51, 51));
        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        jPanel1.add(btnRelatorio);
        btnRelatorio.setBounds(50, 620, 285, 50);

        btnInformacoes.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        btnInformacoes.setForeground(new java.awt.Color(51, 51, 51));
        btnInformacoes.setText("Informações");
        btnInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnInformacoes);
        btnInformacoes.setBounds(50, 700, 285, 50);

        btnMenu.setBackground(new java.awt.Color(250, 52, 25));
        btnMenu.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(51, 51, 51));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu);
        btnMenu.setBounds(50, 300, 285, 50);

        btnCadastro.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(51, 51, 51));
        btnCadastro.setText("Cadastro");
        btnCadastro.setToolTipText("");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastro);
        btnCadastro.setBounds(50, 380, 285, 50);

        lblUsuario.setFont(new java.awt.Font("MS UI Gothic", 0, 30)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(243, 225, 182));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("USUÁRIO");
        jPanel1.add(lblUsuario);
        lblUsuario.setBounds(30, 60, 321, 31);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1500, 1051));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Imob_500px.png"))); // NOI18N
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(360, 40, 500, 500);

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(243, 225, 182));
        jLabel6.setText("Contratos Fechados:");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(1050, 690, 390, 50);

        lblComissao.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        lblComissao.setForeground(new java.awt.Color(124, 188, 154));
        lblComissao.setText("0,00");
        jDesktopPane1.add(lblComissao);
        lblComissao.setBounds(1120, 630, 290, 50);

        lblContrato.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        lblContrato.setForeground(new java.awt.Color(124, 188, 154));
        lblContrato.setText("0");
        jDesktopPane1.add(lblContrato);
        lblContrato.setBounds(1100, 750, 290, 50);

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(243, 225, 182));
        jLabel8.setText("Media Total Comissao:");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(1050, 570, 390, 50);

        lblCedula1.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        lblCedula1.setForeground(new java.awt.Color(124, 188, 154));
        lblCedula1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCedula1.setText("R$");
        jDesktopPane1.add(lblCedula1);
        lblCedula1.setBounds(1050, 630, 60, 50);

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(243, 225, 182));
        jLabel9.setText("Valor Total Comissao:");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(1040, 420, 390, 50);

        lblCedula2.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        lblCedula2.setForeground(new java.awt.Color(124, 188, 154));
        lblCedula2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCedula2.setText("R$");
        jDesktopPane1.add(lblCedula2);
        lblCedula2.setBounds(1040, 490, 60, 50);

        lblTotal.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(124, 188, 154));
        lblTotal.setText("0,00");
        jDesktopPane1.add(lblTotal);
        lblTotal.setBounds(1110, 490, 290, 50);

        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setText("Administrador");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cadeado.png"))); // NOI18N
        jMenuItem1.setText("Controle de Acesso");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame f : jDesktopPane1.getAllFrames()) {
            f.dispose();
        }
        InternalCadastro telaCad = new InternalCadastro().getInstance();
        telaCad.pack();
        if (!telaCad.isVisible()) {
            jDesktopPane1.add(telaCad);
            telaCad.setVisible(true);
            try {
                //telaCad.setMaximum(true);
                telaCad.setSelected(true);
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        } else {
            telaCad.moveToFront();
        }
        this.btnCadastro.setBackground(Color.decode("#fa3419"));
        this.btnSimulacao.setBackground(Color.decode("#f3e1b6"));
        this.btnContrato.setBackground(Color.decode("#f3e1b6"));
        this.btnInformacoes.setBackground(Color.decode("#f3e1b6"));
        this.btnRelatorio.setBackground(Color.decode("#f3e1b6"));
        this.btnMenu.setBackground(Color.decode("#f3e1b6"));
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnSimulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulacaoActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame f : jDesktopPane1.getAllFrames()) {
            f.dispose();
        }
        InternalSimulacao tela = new InternalSimulacao().getInstance();
        tela.pack();
        if (!tela.isVisible()) {
            jDesktopPane1.add(tela);
            tela.setVisible(true);
            try {
                //tela.setMaximum(true);
                tela.setSelected(true);
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        } else {
            tela.moveToFront();

        }
        this.btnSimulacao.setBackground(Color.decode("#fa3419"));
        this.btnContrato.setBackground(Color.decode("#f3e1b6"));
        this.btnCadastro.setBackground(Color.decode("#f3e1b6"));
        this.btnInformacoes.setBackground(Color.decode("#f3e1b6"));
        this.btnRelatorio.setBackground(Color.decode("#f3e1b6"));
        this.btnMenu.setBackground(Color.decode("#f3e1b6"));

    }//GEN-LAST:event_btnSimulacaoActionPerformed

    private void btnContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratoActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame f : jDesktopPane1.getAllFrames()) {
            f.dispose();
        }
        InternalContrato tela = new InternalContrato().getInstance();
        tela.pack();
        if (!tela.isVisible()) {
            jDesktopPane1.add(tela);
            tela.setVisible(true);
            try {
                //tela.setMaximum(true);
                tela.setSelected(true);
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        } else {
            tela.moveToFront();

        }
        this.btnContrato.setBackground(Color.decode("#fa3419"));
        this.btnSimulacao.setBackground(Color.decode("#f3e1b6"));
        this.btnCadastro.setBackground(Color.decode("#f3e1b6"));
        this.btnInformacoes.setBackground(Color.decode("#f3e1b6"));
        this.btnRelatorio.setBackground(Color.decode("#f3e1b6"));
        this.btnMenu.setBackground(Color.decode("#f3e1b6"));

    }//GEN-LAST:event_btnContratoActionPerformed

    private void btnInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacoesActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame f : jDesktopPane1.getAllFrames()) {
            f.dispose();
        }
        InternalInformacoes tela = new InternalInformacoes().getInstance();
        tela.pack();
        if (!tela.isVisible()) {
            jDesktopPane1.add(tela);
            tela.setVisible(true);
            try {
                //tela.setMaximum(true);
                tela.setSelected(true);
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        } else {
            tela.moveToFront();
            /*try {
                tela.setMaximum(true);
                tela.setSelected(true);
            } catch (Exception e2) {
                e2.printStackTrace();
            }*/
        }
        this.btnContrato.setBackground(Color.decode("#f3e1b6"));
        this.btnSimulacao.setBackground(Color.decode("#f3e1b6"));
        this.btnCadastro.setBackground(Color.decode("#f3e1b6"));
        this.btnInformacoes.setBackground(Color.decode("#fa3419"));
        this.btnRelatorio.setBackground(Color.decode("#f3e1b6"));
        this.btnMenu.setBackground(Color.decode("#f3e1b6"));

    }//GEN-LAST:event_btnInformacoesActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame f : jDesktopPane1.getAllFrames()) {
            f.dispose();
        }

        InternalRelatorio tela = new InternalRelatorio().getInstance();
        tela.pack();
        if (!tela.isVisible()) {
            jDesktopPane1.add(tela);
            tela.setVisible(true);
            try {
                //    tela.setMaximum(true);
                tela.setSelected(true);
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        } else {
            tela.moveToFront();
        }
        this.btnContrato.setBackground(Color.decode("#f3e1b6"));
        this.btnSimulacao.setBackground(Color.decode("#f3e1b6"));
        this.btnCadastro.setBackground(Color.decode("#f3e1b6"));
        this.btnRelatorio.setBackground(Color.decode("#fa3419"));
        this.btnInformacoes.setBackground(Color.decode("#f3e1b6"));
        this.btnMenu.setBackground(Color.decode("#f3e1b6"));


    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame f : jDesktopPane1.getAllFrames()) {
            f.dispose();
        }
        this.btnMenu.setBackground(Color.decode("#fa3419"));
        this.btnCadastro.setBackground(Color.decode("#f3e1b6"));
        this.btnSimulacao.setBackground(Color.decode("#f3e1b6"));
        this.btnContrato.setBackground(Color.decode("#f3e1b6"));
        this.btnInformacoes.setBackground(Color.decode("#f3e1b6"));
        this.btnRelatorio.setBackground(Color.decode("#f3e1b6"));


    }//GEN-LAST:event_btnMenuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
// ao ativar a janela, mude e atualize a data:
        Date data = new Date();
        // atenção ao .toString
        //lblData.setText(data.toString());
        // formatando a data
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        txtData.setText(formatador.format(data));
        totalComissao();
        totalContrato();
        valorComissao();
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        DialogAcesso acesso = new DialogAcesso(this, rootPaneCheckingEnabled);
        acesso.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewIniciar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewIniciar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewIniciar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewIniciar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup(new FlatMaterialOceanicContrastIJTheme());
        UIManager.put("Button.arc", 10);
        UIManager.put("Desktop.background", Color.decode("#263238"));
        UIManager.put("Button.background", Color.decode("#f3e1b6"));
        UIManager.put("btnMenu.background", Color.decode("#f3e1b6"));
        //UIManager.put("Button.FocusColor", Color.decode("#aaa"));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewIniciar().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnContrato;
    private javax.swing.JButton btnInformacoes;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSimulacao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedula1;
    private javax.swing.JLabel lblCedula2;
    private javax.swing.JLabel lblComissao;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel txtData;
    // End of variables declaration//GEN-END:variables
}
