/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Informacao;

/**
 *
 * @author gusta
 */
public class InternalInfoAjuda extends javax.swing.JInternalFrame {

    private static InternalInfoAjuda instance;

    public static InternalInfoAjuda getInstance() {
        if (instance == null) {
            instance = new InternalInfoAjuda();
        }
        return instance;
    }

    /**
     * Creates new form InternalInfoAjuda
     */
    public InternalInfoAjuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(580, 610));
        setMinimumSize(new java.awt.Dimension(580, 610));
        setPreferredSize(new java.awt.Dimension(580, 610));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel1.setText("Ajuda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 80, 100, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
