/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Informacao;

import dao.ConnectionFactory;
import dao.UsuarioDAO;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author gusta
 */
public class InternalInfoCadVendedor extends javax.swing.JInternalFrame {

    private static InternalInfoCadVendedor instance;
    private Connection conn;

    public static InternalInfoCadVendedor getInstance() {
        if (instance == null) {
            instance = new InternalInfoCadVendedor();
        }
        return instance;
    }

    /**
     * Creates new form InternalInfoPessoas
     */
    public InternalInfoCadVendedor() {
        initComponents();
        conn = ConnectionFactory.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtPesqCpf = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdImovel = new javax.swing.JTextField();

        setTitle("Vendedores Cadastrados");
        setMaximumSize(new java.awt.Dimension(580, 610));
        setMinimumSize(new java.awt.Dimension(580, 610));
        setPreferredSize(new java.awt.Dimension(580, 610));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 225, 182));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vendedores Cadastrados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 570, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 510, 260);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(124, 188, 154));
        jLabel2.setText("Filtrar por CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 150, 30);

        txtPesqCpf.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        getContentPane().add(txtPesqCpf);
        txtPesqCpf.setBounds(30, 150, 230, 30);

        jToggleButton1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jToggleButton1.setText("Visualizar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(30, 480, 510, 50);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(124, 188, 154));
        jLabel3.setText("Selecionar ID do Imovel");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 120, 190, 30);

        txtIdImovel.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtIdImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdImovelActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdImovel);
        txtIdImovel.setBounds(310, 150, 230, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma impressão?", "ATENCÃO", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                HashMap filtro = new HashMap();
                filtro.put("vendedor", txtPesqCpf.getText());
                filtro.put("idImovel", txtIdImovel.getText());
                JasperPrint print = JasperFillManager.fillReport("C:/Users/gusta/Documents/Relatorios/Ficha_Cadastro_Imovel.jasper", filtro, conn);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtIdImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdImovelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtIdImovel;
    private javax.swing.JTextField txtPesqCpf;
    // End of variables declaration//GEN-END:variables
}
